### ISSUE TITLE
Update kafka clients instrumentation. 

### ISSUE THREAD

**Issue by SimunKaracic** [kamon-io/Kamon#1046]
With the latest version (`2.8.0`), we're getting the following error: 
`ERROR 2021-06-22 23:55:05  Logger : Error => org.apache.kafka.clients.consumer.KafkaConsumer with message Cannot locate field named groupId for class org.apache.kafka.clients.consumer.KafkaConsumer. Class loader: jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68: java.lang.IllegalStateException: Cannot locate field named groupId for class org.apache.kafka.clients.consumer.KafkaConsumer`

In the `KafkaConsumer` class,  `groupId` field was changed from a `String` to an `Optional<String>`, which is causing this issue

**Comment by ivantopo** [comment]
I'm closing this issue because I'm pretty sure it was fixed already. I got it running without problems so far.

**Comment by Randerspl** [comment]
Hello, i was implementing Kamon for Lagom application (v1.6.7) in minikube and i got same exception like in this issue when added kafka instrumentation (im not using kamon bundle just manually adding dependencies).

I was using newest kamon (2.5.12 and kanela 1.0.16) on bitnami/kafka docker image. I used `latest` for kafka docker-compose and it downloaded newest kafka image (i think 3.3.1). After running pod im getting same exception like one posted in this issue. 
On kamon status page then i see that under "Active" is red cross icon but in Instrumentation Modules table all entries are green (even kafka instrumentation).

I changed kafka docker image to older one (2.7.0 or 2.2.0) but i didn't delete kafka volume so i don't know if something from new kafka is still in data and error appears again because of it.

I didn't check if metrics are generated properly for kafka.
