### ISSUE TITLE
Upgrade okhttp3 to 4.x for `kamon-prometheus`

### ISSUE THREAD

**Issue by t-bast** [kamon-io/Kamon#1183]
Kamon currently depends on an old version of okhttp3 (see `Build.scala`):

```scala
val okHttp            = "com.squareup.okhttp3"  %  "okhttp"          % "3.14.7"
```

This creates issues with other packages such as `com.softwaremill.sttp.client3:okhttp-backend` who have upgraded to `okhttp3` version `4.9.3`: adding a dependency to `kamon-prometheus` effectively downgrades the `okhttp` package in my class path, which breaks my application.

It would be really nice to upgrade Kamon to the latest version of `okhttp3`, is this something you could consider?

**Comment by eyalfa** [comment]
hi, we've encountered this issue due to compliance requirements (see square/okhttp#6724).

we were able to mitigate by simply introducing the latest okhttp version as a direct dependency of our application, tested by accessing the kamon-prometheus endpoint in a browser).

will you guys be willing to accept a (tiny) PR increasing okhttp version?
