### ISSUE TITLE
Future of Kamon due to akka license change

### ISSUE THREAD

**Issue by dr3s** [kamon-io/Kamon#1207]
Given the license change with Akka, I'm concerned what the impact is on Kamon.  Will Kamon get an exception like Play? Or how will Kamon deal with the license change?

**Comment by ivantopo** [comment]
Hey @dr3s,

I would love to get proper legal advice on this, but while we get, here is my interpretation of the new license:
  - There is a special grant for Play Framework that ensures Play Framework users can continue to use Akka in production (under the hood of Play) without requiring a commercial license. We initially thought we might need something similar, but we shouldn't need such a special grant because Kamon does not use Akka under the hood. 
  - A license (either free or paid) is required to run applications that use Akka in production, but Kamon does not "run" by itself. Our end users are the ones running Akka applications; thus, getting the proper license for their companies is up to them.

We will continue to publish Kamon Telemetry versions that support the latest Akka versions for as long as the license allows for it. On the Kamon APM side, we are using Akka HTTP on a handful of services and they will get migrated off of Akka HTTP. We are happy with [Armeria](https://armeria.dev/) in several services and might move everything to it, but that is to be seen.

All in all, Kamon Telemetry will continue its aim to be the default telemetry library for the Scala ecosystem! If anything, this gave us the push we needed to bring support for other libraries and frameworks, and expand to serve the entire Scala community, not only the Play/Akka folks.

**Comment by dr3s** [comment]
Thanks for the quick response and I should have checked the code first.  I was thinking you might be using akka in the reporters but it doesn't appear to be the case.  Glad to hear you have a plan for APM as well!

It would be great to hear your plans around other streaming libraries.

**Comment by yarosman** [comment]
@ivantopo Hello. Therefore what about kamon armeria supporting?) Do you have plan to finish pull request with armeria instrumentation ?
