### ISSUE TITLE
Create a kamon-netty module

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#121]
http://www.atetric.com/atetric/javadoc/io.netty/netty-common/4.0.0.Alpha6/io/netty/monitor/package-summary.html

https://github.com/netty/netty/issues/876

https://github.com/netty/netty/issues/718

http://search.maven.org/remotecontent?filepath=io/netty/netty-metrics-yammer/4.0.0.Alpha8/netty-metrics-yammer-4.0.0.Alpha8-sources.jar

https://github.com/netty/netty/issues/922

https://github.com/netty/netty/pull/780

https://github.com/netty/netty/commit/ddd0734f431bb33a3ec3e7cd1aa7d3d85578db96

https://developer.jboss.org/wiki/Netty4AndJMXIntegration

https://github.com/netty/netty/issues/4981

https://github.com/netty/netty/pull/5397

https://github.com/netty/netty/pull/4666

https://github.com/netty/netty/issues/3824

https://github.com/twitter/finagle/issues/506

**Comment by dpsoft** [comment]
Some ideas:
- [ ]  Number of Threads used in a EventLoopGroup
- [ ] How many Channels are registered in an EventLoop
- [ ] Execution times for an event loop run
- [ ] Does Selector.select(..) unblock before the timeout is reached
- [ ]  Metrics about operations on the ChannelPipeline
- [ ] Throughput

**Comment by magro** [comment]
In our loadtests we saw quite high response times (1 - 10 sec) in the proxy (nginx) for some kinds of requests, while kamon-play reports 100 - 200 millis for the related routes. Therefore we wonder, if there's some limitation in netty causing these higher response times. It would be great to have some metrics as near to the networking stack as possible. Just dropping this here, as I'm not sure which of the metrics mentioned above would help in this situation. (We're also not continuing to analyze this, because the tested load was in ranges that we don't really expect to see in the near future.)

**Comment by dpsoft** [comment]
closed with https://github.com/kamon-io/kamon-netty/pull/1
