### ISSUE TITLE
cats-effect IO traces aren't joined up in 3.4.0-RC1

### ISSUE THREAD

**Issue by m50d** [kamon-io/Kamon#1210]
Just to flag up that our spans are not being linked to parents under 3.4.0-RC1 - presumably due to some changes to the IO implementation where we hook into it. I haven't looked into the details yet.

**Comment by ivantopo** [comment]
Hey @dispalt @m50d, may I ask what frameworks are you using in the app where this problem is happening?

I took a look at the diff and it seems like the only instrumentation that will be missing is the one capturing the context when a new IOFiber is created:
![image](https://user-images.githubusercontent.com/1302854/195401240-42cbdc20-f510-4a1d-9cac-f489acc2d448.png)

That's because of a different number of arguments in the constructor. I opened a [PR](https://github.com/kamon-io/Kamon/pull/1214) that should be fixing this.

**Comment by dispalt** [comment]
> Hey @dispalt @m50d, may I ask what frameworks are you using in the app where this problem is happening?

We use Play to serve requests and all the biz logic is usually using an IO underneath.

**Comment by ivantopo** [comment]
Thanks for the answer, @dispalt. This is exactly the case I'm covering on #1214.

**Comment by dispalt** [comment]
> Thanks for the answer, @dispalt. This is exactly the case I'm covering on #1214.

Awesome... thank you!

**Comment by ivantopo** [comment]
Closing this as fixed on #1214. Released as Kamon Telemetry 2.5.9
