### ISSUE TITLE
ActorSystem won't start with 0.3.6-5456e7ca8f215b2a3a5bdbd3177a6ae61f268eef

### ISSUE THREAD

**Issue by nilsga** [kamon-io/Kamon#177]
I decided to try the latest 0.3.6 snapshot (0.3.6-5456e7ca8f215b2a3a5bdbd3177a6ae61f268eef) to see if the dispatcher stats had improved, but now the `ActorSystem` fails on the `create` call. It hangs for a while, and then it throws a `RuntimeException: Kamon has not been started yet`. I have not changed any configuration from 0.3.5.

**Comment by ivantopo** [comment]
Hello @nilsga, the new release will require our users to "start" Kamon by calling `Kamon.start(...)` as early as possible in your application. If you are using Akka then ideally you should start Kamon before creating your ActorSystem so that Kamon will be ready to work when the Akka instrumentation kicks in. 

That should solve your issue, please let us know if you have any further problems!

**Comment by ivantopo** [comment]
Oh and of course, thanks for trying our latest snapshot! We really appreciate that you take time to try it and provide us with feedback :D.

**Comment by nilsga** [comment]
Thanks. Got a little further now, but now I'm getting `java.lang.NoSuchMethodException: kamon.metric.Metrics.<init>()` during startup instead.

**Comment by ivantopo** [comment]
can you please post the full stacktrace that produced that error? also, can you describe a bit your environment? It seems like this kind of error is found when trying to call a non-existent default constructor using reflection which we are certainly not doing, is it possible that your code starting Kamon in some weird way?

**Comment by nilsga** [comment]
I have not done anything special. I have followed the documentation as I have understood it. I believe the problem now is the `Metrics` extension in the configuration: `extensions = ["kamon.metric.Metrics", "kamon.statsd.StatsD"]` If I remove it, the error disappears, but I can't seem to get any metrics reported.

**Comment by nilsga** [comment]
The log reporter seems to confirm that there are no metrics: `No metrics reported`. I guess it's just my configuration that is not adapted to the latest snapshot. Do you have some pointers on what have changed, especially configuration wise?

**Comment by ivantopo** [comment]
Oh, that must be it! In this new release you don't need to add the Kamon extensions to the `akka.extensions` configuration key, but we rather have our own mechanism to auto-start Kamon extensions. Please remove anything related to Kamon from that key and ensure that `Kamon.start(...)` is called promptly after your app started. You should see some DEBUG logs where Kamon says it is auto-starting it's modules. You just need the `kamon-statsd` module to be on the classpath for Kamon to auto-start it.

**Comment by ivantopo** [comment]
With regards to the configs, yes we do have some changes! First, it is `kamon.metric` instead of `kamon.metrics`, second, the filters in the `kamon.metric.filters` section have different categories for the akka-related stuff as they are now called `akka-actor`, `akka-router` and `akka-dispatcher`.. finally, all these entity names are now scoped with the ActorSystem name to which they belong, as now Kamon will have it's own internal ActorSystem which is separate from the one in your application.. if you had `user/*` in the previous version version then now you need `my-actor-system-name/user/**` to get the same filter. 

Take a look at [this] section of our upcoming docs to know how the pattern matcher works.

[this]: https://github.com/kamon-io/kamon.io/blob/master/core/metrics/core-concepts.md#filtering-entities

**Comment by ivantopo** [comment]
This might help as well: https://github.com/kamon-io/Kamon/blob/master/kamon-akka/src/main/resources/reference.conf#L17

**Comment by nilsga** [comment]
Yeah, I see to log statements:

```
[INFO] [04/03/2015 18:31:45.810] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[INFO] [04/03/2015 18:31:45.898] [main] [LogReporterExtension(akka://kamon)] Starting the Kamon(LogReporter) extension
```

However, still no metrics reported. I have added the `kamon-akka_2.11` dependency. I have this configuration related to kamon:

```
kamon {
  statsd {
    hostname = "localhost"
    port = 8125
  }
  metrics {
    filters = [
      {
        actor {
          includes = [ "*" ]
          excludes = []
        }
      },
      {
        trace {
          includes = [ "*" ]
          excludes = []
        }
      },
      {
        dispatcher {
          includes = [ "*" ]
          excludes = []
        }
      }
    ]
  }
}
```

**Comment by ivantopo** [comment]
Please see two comments bellow :), bad timing!

**Comment by nilsga** [comment]
Thanks, it works now, after changing the filters according to the reference. I can now see the metrics in the statsd process in the docker image. Still can't get the metrics into grafana, but that's probably not related to this issue.

**Comment by ivantopo** [comment]
Excellent! If you already had some dashboards running in grafana then you will need to update the metric query patters from the old `akka`, `router` and `dispatcher` names to the newer ones with the `akka-` preffix. Also for dispatchers we now have metrics which are specific to thread-pool-executors or -fork-join-pools and you might want to adjust them accordingly.
