### ISSUE TITLE
Generalize Histogram and Gauge traits

### ISSUE THREAD

**Issue by StefanGheorghiu** [kamon-io/Kamon#181]
Currently, Histogram and Gauge interfaces are equal/similar. It would be convenient to introduce a supertype grouping common method signatures of the both.

**Comment by pjan** [comment]
Mind to elaborate why so?

**Comment by aalleexxeeii** [comment]
At least not to double operations in 3rd-party extension APIs: instead of having two sets of methods that differ only in the parameter type Histogram/Gauge but have absolutely identical bodies, they could be generalized by the base class.

**Comment by pjan** [comment]
hmm; I'm not a big fan of type hierarchies. I have a hard time finding an "is-a"-relationship that would have both a `Gauge` and a `Histogram` as their descendants, that isn't the already existing `Metric`.

It could be done with a `Recording` trait perhaps, that both classes mix in, and this change is easy enough to put up a simple PR for it. I'm still not sure about the added value.

If you want to avoid duplication in your library because of the parameter type, you can still resort to Existential types to get around that?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
