### ISSUE TITLE
mailbox-size statistics are reported to statsd as timers

### ISSUE THREAD

**Issue by jamesmulcahy** [kamon-io/Kamon#182]
I'd have expected these to be counters, or gauges -- but I see them appear under the timers section in the stats that carbon is storing from StatsD.

e.g.

stats/timers/REDACTED/REDACTED/akka-actor/REDACTED-ACTOR-NAME/mailbox-size/count.wsp

**Comment by ivantopo** [comment]
Hey James, the reason is that we internally track the mailbox-size using a `min-max-counter`, which in turn stores the minimum, maximum and current mailbox size in a fixed interval (100ms by default).. if you keep the default tick interval of 10 seconds in Kamon, it means that every time we flush data to StatsD we have around 300 datapoints for each mailbox. If we were to report them as a gauge, only the last value we send would be preserved and if we were to report them as a counter, all the values will be added together into one big sum. Sending them as timers is the only way to get some value out of this data with StatsD. 

I'd like to add that the name `timer` is kind of misleading, as it is really working with "distribution of values" that might not be related to time at all.. well, that's how it works!
