### ISSUE TITLE
Take a look at supporting OSGi

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#209]
We will need to do a bit of investigation on what should be done to support people using Kamon in a OSGi container. I know we should add some bits to the manifest included in our artifacts but given all the classloader magic that happens with OSGi we will need to do some additional experimentation on how to setup the weaver in those environments. 

Also, publishing a simple example that works might be of great help to our users. See this thread as well: https://groups.google.com/forum/#!topic/kamon-user/N4bKK2Vv-jk

**Comment by antonsarov** [comment]
As I am the one who started the thread on the user group I wanted to keep this running so I created some base which can be used for investigations (https://github.com/antonsarov/kamon-osgi). Both parts can be imported into Eclipse. There is one part in the Activator.java which has to be adapted. The mixture between Java and Scala is on purpose, as is the project's separation - to "simulate" some real world scenarios.

I hope this helps as a starting point

**Comment by PhilAndrew** [comment]
+1, sad - I use OSGi and have no idea how to get it to work.

**Comment by anatoliy-balakirev** [comment]
Hi.
I've adjusted kamon-core a bit, to make it osgi ready. Check this branch if you're interested:
https://github.com/anatoliy-balakirev/Kamon/tree/kamon_core_osgi_ready
Still testing it, but looks ok so far.
However, the most interesting part is about load time weaving, which I didn't manage to adjust for OSGI yet...

**Comment by PhilAndrew** [comment]
I'll take a look tomorrow (Monday).

**Comment by anatoliy-balakirev** [comment]
So I tried to make kamon-akka osgi ready too.
I've checked how they did load time weaving in equinox, thrown away stuff I don't need (it doesn't need to be so generic for me), adjusted that code to work not with proprietary equinox's implementation, but with standard OSGI's WeavingHook instead and plugged that code into kamon-akka. My repo is here:
https://github.com/anatoliy-balakirev/kamon-akka

So far it looks ok, my "agent" is started, it's reading aspects from aop.xml, weaving them into akka module, but later I'm getting following:
Caused by: java.lang.NoSuchMethodError: akka.kamon.instrumentation.ActorLoggingInstrumentation.aspectOf()Lakka/kamon/instrumentation/ActorLoggingInstrumentation;

After some googling it turned out, that those aspect classes are not converted into aspects. This is because in kamon-akka they were converted into aspects during load time weaving by provided weaving agent. However, for my case it doesn't work, because my weaving agent is not handling those aspects (they are part of that agent itself). So in order to fix that I need to integrate sbt-aspectj (https://github.com/sbt/sbt-aspectj) into kamon-akka and compile those aspects at compilation time. I've spent some time trying to integrate that plugin, but with no luck. Compilation is done, but weaving task is not started. Eventually I don't have any aspects compiled and getting empty jar.

I've never used neither scala, nor sbt before, so will appreciate any help with that. Otherwise I'm stuck at such a stupid easy step and don't really know what to do next...

I've tried to add that plugin and configuration as follows:
https://github.com/anatoliy-balakirev/kamon-akka/commit/3a903696821fbe60b37aa8f28015d78271ac69e4

**Comment by anatoliy-balakirev** [comment]
FYI: Created pull request for kamon-core:
https://github.com/kamon-io/Kamon/pull/442
For kamon-akka I gave up for now. Waiting for some help there :)

**Comment by PhilAndrew** [comment]
I havn't yet looked into your kamon-akka problem but I'll give you some potential hint, I got Akka running under OSGi in my project but to do so I had this bug https://github.com/akka/akka/issues/18846 and solved it with the code in this package https://github.com/PhilAndrew/JumpMicro/tree/master/JMSangriaGraphql/src/main/scala/jumpmicro/shared/util/akkaosgi

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
