### ISSUE TITLE
Make it configurable to include identification tags in the datadog module.

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#210]
For some users have the automatically generated `entity-category=entity-name` tag in datadog is nice, but for some others it can be pain, so, we should make it configurable and let the users decide what they want! Take a look at the comments in #188. 

Also, it might be of help to allow users to provide their own metric name and tags generator, the very same way we do in the StatsD module.

**Comment by toddkazakov** [comment]
@ivantopo is there any update on this issue? We're running a kubernetes cluster and using kamon for traces and system metrics. 

Traces work really nice, because we can tag them with the pod name (implemented in 0.6.1). On the other hand, though, system metrics are pretty much unusable, because we cannot apply any tags. I'm happy to follow a similar approach with the statsd module - adding a new `KeyMetricGenerator`.

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
