### ISSUE TITLE
Akka 2.4 M1 support

### ISSUE THREAD

**Issue by kailuowang** [kamon-io/Kamon#215]
I understand that Kamon doesn't support Akka 2.4 yet, and you can't run the current Kamon 0.4.0 released binary against  an Akka 2.4 M1 based app. 
I compiled the Kamon 0.4.0 release against the Akka 2.4 M1 , and it seems working fine. 
So here is the branch I created for the compilation. 
https://github.com/kailuowang/Kamon/tree/release-akka-2.4
I gave it a version 0.4.0_akka-2.4
Can we release a special Kamon snapshot for Akka 2.4? 
Thanks!

**Comment by ivantopo** [comment]
Hello @kailuowang, thanks a lot for sharing your experiment! I had to do some minor changes to actually publish as shown in 35bb09838d1b0a2a1e36cd68c2db158b728a2981, but the artifacts are now in the snapshots repo, please take a look at this post: http://kamon.io/teamblog/2015/06/14/welcome-akka-2.4-goodbye-akka-2.2/

If it wasn't because of your feedback, we would probably had waited a lot more before experimenting with Akka 2.4, there will be more than one happy user :D, regards!

**Comment by kailuowang** [comment]
Thanks very much for the snapshot release. Glad that I did a little help to a great product you guys are building.
