### ISSUE TITLE
provide proper support for Akka's Stash functionality

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/Kamon#252]
Taken from this thread: https://groups.google.com/forum/#!topic/kamon-user/yHxDGPHf3YM

I just realized that you will get some sort of unexpected metrics when messages are stashed: When a message arrives for the first time it is measured as any normal message would, meaning that the time-in-mailbox and processing-time metrics are recorded. If the message is stashed then the whole Envelope is kept in the stash and once unstashed then the messages are put back into the mailbox, meaning that they will go again through the normal processing path and the time-in-mailbox and processing-time metrics will be recorded again, but this time, since the envelope is the same as the initial one then the time-in-mailbox that gets recorded is not counting since the message was stashed or put back in the queue, but rather since it was initially put in the actor's mailbox. 

To me, that time-in-mailbox measurement is really unexpected, specially because it is very likely that stashed-time will have a different behavior to actual time-in-mailbox for a given actor and mixing both kinds of recordings in the same metric will render it useless.. now, how to solve this issue? my current idea would be add a new metric called "time-in-stash" that would reflect exactly what it says and additionally reset the capture time on the envelope so that once a message is unstashed and put back into the mailbox the time-in-mailbox will again reflect exactly what it is, the time in the mailbox :)

**Comment by magro** [comment]
Hi guys, I'm still a very happy user of kamon, just without any issues/questions for a long time :-)

In my current project we're using [eventuate](https://github.com/RBMHTechnology/eventuate), which is built in top of Akka. These days we experienced weird measurements: time-in-mailbox.max was up to 30 seconds, time-in-mailbox.p99 was below 100 millis, processing-time.max was also below 100 millis and count was s.th. around 1k (out of my head, values might slightly differ). 

Because eventuate stashes messages as long as it's persisting an event to Cassandra, the assumption is that the weird measurements can be explained with this ticket here. Please note that eventuate uses some kind of a [hierarchical, custom stash](https://github.com/RBMHTechnology/eventuate/blob/master/eventuate-core/src/main/scala/akka/actor/MessageStash.scala) to support both its own stashing and the user stashing messages.

I'd assume that this ticket here alone would not solve our issue. What would you recommend how to proceed?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
