### ISSUE TITLE
Web support for Undertow seems missing :(

### ISSUE THREAD

**Issue by gxbe** [kamon-io/Kamon#265]
I am in love with (HDR) Histogram but I want to support Wildfly.  If you look you will see Undertow is dominating the HTTP server benchmarks, at least for the JVM, so I am just wanting to recommend that it might be a good candidate for Web/HTTP support in future versions of Kamon.

http://www.techempower.com/benchmarks/#section=data-r10&hw=peak&test=json

**Comment by dpsoft** [comment]
Hi @gxbe to be honest, I dont have experience with Undertow, but I think is posible with a simple approach how to create a [Handler] in order to capture some [Metrics] and create a [Trace] with the incoming requests with the Kamon API. Also you can take a look [here] in order to show a complete example.

[Handler]: https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/MetricsHandler.java
[Metrics]:http://kamon.io/core/metrics/instruments/
[Trace]:http://kamon.io/core/tracing/core-concepts/
[here]:http://kamon.io/teamblog/2015/08/08/twenty-minutes-in-the-playground-monitoring-scalatra-with-kamon/

**Comment by gxbe** [comment]
Thanks I appreciate the help.  I think you're right it seems I should be able to instrument that class just by making a couple of method calls.  If I end up going this route then I'll submit a pull request.
