### ISSUE TITLE
allow to have dots '.' in statsd keys

### ISSUE THREAD

**Issue by jozic** [kamon-io/Kamon#266]
default key normalization strategy in kamon replaces dots (`.`) with underscores (`_`). But dot is special if you use statsd with graphite. And sometimes it may be desired to have dots in your keys.

To my understanding original problem with dots was host names and/or some akka actor/dispatcher names (which can have dots). So not replacing dots there can cause another problem. 

The possible solution is to allow for some configurable `encoding` of dots. Something like 

somewhere in config

```
normalization-strategy {
  replace-with-dots = "_DOTS_"
}
```

and then you can emit you custom statsd keys like
`counter("my-service-failure_DOTS_down")`
`counter("my-service-failure_DOTS_invalid-params")`
which will be normalized to 
`my-service-failure.down` and `my-service-failure.invalid-params`
which in turn will allow to query keys like 
`my-service-failure`
`my-service-failure.down`
`my-service-failure.invalid-params`

**Comment by ivantopo** [comment]
hey @jozic! I do see what you mean here and certainly, when the only backend you are using is the StatsD module or if maybe you are using Kamon as a replacement for another StatsD client, then having dots in entity names becomes a more natural or even necessary thing to do.

As you said, hostnames and dispatcher names are the most common cases of "undesired" dots in a metric name, as it will shift the paths in Graphite and prevent people from seeing data with the default dashboards. But, rather than having the "_DOTS_" notation, I would just say that people needing this could create a custom key name generator that only replaces dots if the entity category is `akka-dispatcher` and that's it.. or, maybe closer to what I think is your need, a custom key generator that normalizes everything BUT single instrument entity recorders (the ones you get from `.counter(...), .histogram(...)` and so on).

I have seen this need before and we should add this setting to our key generator, but in the meantime I think you can solve it with a custom generator... hope the info helps, regards!

**Comment by jozic** [comment]
you are right @ivantopo, we do use custom generator. But i created this issue so that people can just use some existing solution instead of rolling out their own. In other words, it's a `nice to have` feature

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
