### ISSUE TITLE
Slick support in jdbc module

### ISSUE THREAD

**Issue by frossi85** [kamon-io/Kamon#311]
Because Slick is the default option to work with databases in Scala, it would be nice to have an instrumentation that not require code to measure the queries time. What do you think about it?

I can contribute with coding if you feel that is a good idea.

**Comment by dpsoft** [comment]
Hi @frossi85 that could be a good idea, but currently kamon has a module that can extract metrics related to jdbc queries in a generic way: [kamon-jdbc], but nothing specific to slick or other framework. 
but please, share with us what do you have in mind?

[kamon-jdbc]:https://github.com/kamon-io/Kamon/tree/master/kamon-jdbc/src

**Comment by shayangz** [comment]
is there any documentation on how to use this module? I couldn't find it on kamon.io

**Comment by dpsoft** [comment]
@frossi85 @shayangz we need more time in order to complete de documentation :(, please take a look at the following example:

***kamon-jdbc + play example***
to run the provided example we need do the following:
1 - uncompress the tar
2 - sbt -> aspectj-runner:run
3 - curl "http://localhost:9000/createTable"
4 - curl "http://localhost:9000/insertRecord"
5 - curl "http://localhost:9000/findAllRecords"
6 - shold print in the console something like this:
```
[bla-bla-bla] kamon.jdbc.DefaultSlowQueryProcessor - The query [SELECT * from Address; CALL 
SLEEP(3000)] took 3001 ms and the slow query threshold is 2000 ms
```
Two more important things :
** We need provide a minimal aop.xml file in the in the META-INF folder that will tell the AspectJ Weaver to actually scan your project classes to apply the instrumentation. Your file might look like this:
```
<aspectj>
    <weaver options="-Xlint:ignore">
        <include within="*"/>
        <exclude within="org.aspectj.*"/>
    </weaver>
</aspectj>
```
Try to keep the filters as specific as possible because all classes matching the provided include filters will be fully scanned to detect if instrumentation should be applied. Having very broad filters (such as **) will significantly increase the startup time as the AspectJ Weaver will have much more work to do on startup.
** In order to playframework find the META-INF directory we need make a jar that contains the aop.xml file inside and put this in the classpath (all this is necessary in order to sort the playframework classloader magic :(), in our case we use the lib directory for unmanaged libraries dependencies.

[kamon-play.zip](https://github.com/kamon-io/Kamon/files/118544/kamon-play.zip)

**Comment by frossi85** [comment]
the creation of this issue was because I could not make work the kamon-jdbc module with slick. Then my first thought was to think that was a problem related with slick, but now I am sure that is a configuration problem. I will see your example.

But now I think that could be cool have a metric related with de query compilation time to look those queries that takes too much time and tranform they to compiled queries. I will think in other potential metrics.

Thanks for the example, when I have time I will create a PR in the Kamon Page project to add some documentation to use this module if you want.

**Comment by dpsoft** [comment]
@frossi85 todos los PR son bienvenidos y mas los relacionados con la documentación ;) y si te parece buena idea tener métricas especificas a Slick armate algo y lo charlamos. 

Saludos.

**Comment by frossi85** [comment]
@dpsoft el proyecto de play+jdbc+kamon no me compilo. Trate de llevarlo a un proyecto que estoy haciendo con akka-http pero no logro encontrar la métrica para agregarla a Grafana, por lo que creo que no esta reportando. El proyecto es para dar una charla en SUGAR, todavia le falta laburo, y quería incluir Kamon, si me ayudas a integrarlo después yo puedo escribir la documentación del modulo de jdbc.

Lo proximo es ver si puedo hacerlo funcionar con akka-http para que reporte los tiempos de las requests.

**Comment by dpsoft** [comment]
@frossi85 avisme en que te puedo ayudar ;)

**Comment by dpsoft** [comment]
I think is posible to add some extension in order to get the same metrics provided actually by ```kamon-jdbc``` without much effort:

```scala

import kamon.trace.{TraceContextAware, Tracer}
import slick.util.AsyncExecutor

import scala.concurrent.ExecutionContext

class RunnableContextAware(underlying: Runnable) extends TraceContextAware with Runnable {
  private val traceContext = Tracer.currentContext

  override def run(): Unit = {
    Tracer.withContext(traceContext) {
      underlying.run()
    }
  }
}
case class ExecutionContextAware(underlying:ExecutionContext) extends ExecutionContext {
  override def execute(runnable: Runnable): Unit = underlying.execute(new RunnableContextAware(runnable))
  override def reportFailure(cause: Throwable): Unit = underlying.reportFailure(cause)
}

case class AsyncExecutorContextAware(underlying:AsyncExecutor) extends AsyncExecutor {
  override def executionContext: ExecutionContext = ExecutionContextAware(underlying.executionContext)
  override def close(): Unit = underlying.close()
}

```

and with aspectj only need wrap the executor like this:
```scala
Database.forURL(databas, driver="org.h2.Driver", executor = AsyncExecutorContextAware(AsyncExecutor.default()))

```

**Comment by spacer59** [comment]
Is Slick support planned to be released anytime soon?

**Comment by ivantopo** [comment]
@spacer59 not soon, but definitely at some point in the future. We need to cleanup a bit what we have now before adding more modules and features to Kamon. I would suggest that you watch this issue to be notified when it gets out!

**Comment by Reeebuuk** [comment]
How about now? :D

**Comment by ivantopo** [comment]
hey @Reeebuuk, now seems like a much better time! :wink:

**Comment by Reeebuuk** [comment]
That would be awesome my friend. The fix above just broke our tests and brought nothing good :D

**Comment by boxsterman** [comment]
I would also love to see this issue fixed in order to get consistent zipkin traces. 
@ivantopo Would "now" be an even better time to address it?

**Comment by dominics** [comment]
Is support supposed to work in 2.x? (via https://github.com/kamon-io/kamon-jdbc/blob/829a06d4a3afbd44d1e141f09f03e93afbf50cac/src/main/resources/reference.conf#L74-L76)

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop be our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
