### ISSUE TITLE
TraceContext metadata cannot be accessed

### ISSUE THREAD

**Issue by namiazad** [kamon-io/Kamon#316]
I do not know whether it is a bug or a feature, but it is possible to add meta data to the TraceContext while its getting pass through but it is not possible to read TraceContext metadata (_metadata is private). is it intentional?

**Comment by dpsoft** [comment]
@namiazad sorry for the late response but you can check this [post] in order to understand how to get the metadata information and also I recommend take a look at our TraceLocalStorage feature that isn't documented yet :( but the [tests] maybe can help you.

[post]:https://inoio.de/blog/2014/12/13/how-to-log-slow-requests-with-play2/
[tests]:https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/test/scala/kamon/trace/TraceLocalSpec.scala#L32
