### ISSUE TITLE
Add Custom Kamon.start(config) option.

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#351]

**Comment by dragontree101** [comment]
could you please deploy kamon 0.6.2
i want to hope to use start(config) this feature
thanks very much!

**Comment by dpsoft** [comment]
@dragontree101 for now you can use  the snapshot version that contains the latest in the master repo, please don't forget add our repo: ```"Kamon Repository Snapshots" at "http://snapshots.kamon.io"``` and the artifact is:```0.6.2-b10b1cf2013460c791d5e3f7600fc654145f3d4e```, we need resolve some issues before release the 0.6.2.

**Comment by andrewgee** [comment]
@dpsoft What is the issue with the fix you made? I see you have taken it out.

**Comment by ivantopo** [comment]
Hey @andrewgee, the thing here is that we are introducing a confusing situation by allowing that way of starting Kamon. The main goal when removing the option to use `Kamon.start(config)` was to avoid needing the user to start Kamon to start using it, one of the most common problems we have is people having issues with initialization order, in which some code might be using Kamon before it was started, which is specially painful when writing tests. On the other hand, providing a custom Config object is a useful thing, we are making use of that and some other people as well, that's why when we removed the option to start Kamon with a custom config object we included the `kamon.config-provider` setting, that can be used to provide Kamon with a class of your choice that will provide the proper config object you want to use. That solution is not perfect, but it is consistent. You can always use Kamon without regardless of when you called Kamon.start and if you need to provide a custom config, there is a way to do it.

With the mentioned fix, if you called `Kamon.start(config)` before anything else used Kamon, then it would take the config you provided, but if something else used Kamon before that call, then it will be initialized with the default config sources. That is not consistent and we would just be changing one initialization problem with another.

Until we find some better idea to fix this in which we are not introducing inconsistencies it will be better to remain as it is now. Sorry for the inconvenience :(.. and, of course, drop your ideas here!

**Comment by andrewgee** [comment]
@ivantopo Thanks for the reply. It does seem like a tricky situation to solve!

**Comment by JozoVilcek** [comment]
Sounds a bit weird convenience to me. Are we not, software engineers, destined to battle design of our applications, dependencies, injections, provisioning, what should start first and what second, and what should components get already started?

It is quite limiting for me (not sure if should go into details here). Imagine `AkkaSystem` whould behave the same. You would not be able to do the thing with `internal-config` kamon does, to shield its stuff. I have a similar issue.

It is suboptimal to call `Kamon.start()` which sometimes does what it says and sometimes gets already started instance. Maybe make a distinction here? 

Options I see:

1) Could you support both case? E.g. `Kamon.start()` like it behaves now and it's companion creator/factory, `KamonFactory.start(Config)` or even `KamonFactory.start(ConfigProvider)` which would go and inject under the hood an instance created via supplied configuration into the `Kamon`. Subsequent calls to `Kamon.start()` would return instance created via factory.

2) I am OK with creating my own Kamon start logic which suites me, if supplied with access to modules and other pieces. Currently most of stuff touched inside `Kamon` object are private.

I hope we gets a way to pass configuration soon.

**Comment by mykelalvis** [comment]
I also hope [the documentation](http://kamon.io/introduction/configuration/) gets changed to not include methods that aren't available.... 

I'd PR but there's no indication in the documentation the correct path for that.

**Comment by dpsoft** [comment]
@mykelalvis please do the PR in the [documentation website]

[documentation website]: https://github.com/kamon-io/kamon.io

**Comment by stphngrtz** [comment]
What about reopening the issue since the problem is not yet solved?

**Comment by ivantopo** [comment]
let's keep this one closed and keep an eye on this: https://github.com/kamon-io/Kamon/issues/395
