### ISSUE TITLE
use kamon send histogram to statsd error

### ISSUE THREAD

**Issue by dragontree101** [kamon-io/Kamon#355]
i use kamon 0.5.2 version and use histogram to statsd (statsd is go version [)](https://github.com/bitly/statsdaemon) and statsd has error log : `2016/05/17 14:21:36 invalid line 'rhllor-test-2.first-demo-dev.Dragon_local.histogram.http.get_string_json:1|ms:4|ms|@0.5:5|ms:11|ms:12|ms:23|ms:25|ms:28|ms:32|ms:44|ms:48|ms:58|ms:60|ms:62|ms:71|ms:72|ms:73|ms:75|ms:78|ms:96|ms:100|ms:102|ms'` 

i use kamon api is 
`Kamon.metrics().histogram(key).record(time);`
and i found statsd's protocol is `<metric name>:<value>|ms`

how can i solve this problem? thanks

**Comment by dpsoft** [comment]
@dragontree101 I don't know how is the StatsD go implementation but, we pack multiple measurements in the same packet, not only using the \n separator for full metrics descriptions but a shorter (undocumented) representation in which we found in the StatsD code that allows us to send multiple measurement levels for the same metric without repeating the metric name [1], which helps a lot because usually the metric name represents most of the metrics packets.

I think that you can implements a `kamon.statsd.MetricKeyGenerator`[2] in order to match the go StatsD protocol.
 
[1]: https://github.com/etsy/statsd/blob/master/stats.js#L250
[2]: https://github.com/kamon-io/Kamon/blob/master/kamon-statsd/src/main/resources/reference.conf#L35

**Comment by dragontree101** [comment]
thanks, i find `SimpleStatsDMetricsSender` in kamon 0.6.1
i think this sender can support go StatsD protocol
but, i need `Kamon.start(Config config);` api, but in kamon 0.6.1 not this api
i see you server days ago support this api in 0.6.2 , but 0.6.2 has not deploy, 

i am in china, i can not use sbt to build this project by myself. 
so i hope you can deploy 0.6.2 this version
thanks very much.

**Comment by dpsoft** [comment]
@dragontree101 for now you can use  the snapshot version that contains the latest in the master repo, please don't forget add our repo: ```"Kamon Repository Snapshots" at "http://snapshots.kamon.io"``` and the artifact is:```0.6.2-b10b1cf2013460c791d5e3f7600fc654145f3d4e```, we need resolve some issues before release the 0.6.2.

**Comment by dragontree101** [comment]
thanks, i see in other question, :)
