### ISSUE TITLE
Include tags and status in TraceInfo and SegmentInfo

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#377]

**Comment by bfil** [comment]
I've just tried to add tags to my traces (which are sent to InfluxDB), but I've noticed that only counters and segments tags are working.

I think this change will allow the traces to have tags, so they will be sent on the following line:
https://github.com/kamon-io/Kamon/blob/master/kamon-influxdb/src/main/scala/kamon/influxdb/BatchInfluxDBMetricsPacker.scala#L37

Is that the case? Because at the moment I can see `entity.tags` coming out as an empty `Map`, which seems broken.

Are you getting this released anytime soon?

**Comment by bfil** [comment]
Ok, I've tested this by building it locally and it fixed the issue with missing tags on the main traces, would be great to get this patch released!

**Comment by dpsoft** [comment]
Hey bruno,

we will publish new release soon.... in relation to addTags/removeTags
methods you can use addTag/removeTag ;), are not usefull for you use case?
also the posibility of accesing to the tags in the TraceContext is a good
idea. https://github.com/kamon-io/Kamon/issues/379

Cheers,
Diego

**Comment by bfil** [comment]
@dpsoft 

Sounds great, the only reason behind the `addTags`/`removeTags` method is that usually in code I have a map of tags, and I end up having to deconstruct it in order to use the `addTag`/`removeTag` methods, would be nice to have both API-wise I guess?

If you would accept a PR for the ability to access the `tags` in `TraceContext` I can work on it :)

**Comment by dpsoft** [comment]
Please feel free to make a PR.

**Comment by bfil** [comment]
@dpsoft here it is: https://github.com/kamon-io/Kamon/pull/386
