### ISSUE TITLE
Opentracing Compliant

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#412]
http://opentracing.io/

**Comment by adriancole** [comment]
Are you planning to add a core dependency on OpenTracing (rewrite your internal tracer to be an extension of those interfaces)? Or are you going to just support OpenTracing consumers (expose means to underpin OpenTracing interfaces as powered by your tracer api)? One thing to watch out for is that OpenTracing is not 1.0, yet. There are projects pinned due to different backends being on different versions of <1.0 apis

**Comment by dpsoft** [comment]
@adriancole plese take a look to kamon-core in the branch kamon-1.0-develop which is the one that implements OpenTracing, and yes is influenced by Brave ;)

**Comment by ivantopo** [comment]
Closing this as we went in and out of OT. There will eventually be a kamon-opentracing module but no OT will make it into kamon core for sure.
