### ISSUE TITLE
Centralise asynchttpclient

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/Kamon#429]
There is ongoing work to replace spray-client with asynchttpclient in kamon-influxdb and kamon-spm, as well as an open issue in kamon-newrelic.
It would be nice to have some of the code shared in a common module like kamon-core or maybe, a kamon-asynchttpclient module.

**Comment by ivantopo** [comment]
That's something to consider, for sure, but lately we are trying to spread things instead of centralizing :/... and there is not much code to share for using asynchttpclient anyways, the API is pretty simple and straightforward.

We will consider it for some big refactor that is coming, will let you know, thanks!

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
