### ISSUE TITLE
Cannot monitor mailbox-size metric of routee actors with v0.6.x

### ISSUE THREAD

**Issue by ovunccetin** [kamon-io/Kamon#456]
I was using version **0.5.2** of kamon-akka library, without any problems, to monitor my akka actors. I then upgraded it to **0.6.3** and noticed that some statistics were not sent.

When I looked at the source code, I saw that the **mailbox-size** metric was not sent for routee actors running under a router. Instead, router metrics such as routingTime are being sent for the routee actors. However, I'm using them as workers and need to monitor their mailbox sizes.

I'm not sure if this is a bug, but how can I solve this problem? Are there any configurations or workaround solutions to fix it?

I have also [asked](http://stackoverflow.com/questions/43413006/monitoring-mailbox-size-metric-of-routee-actors-with-kamon-akka-0-6-x) this issue in Stackoverflow.

**Comment by ivantopo** [comment]
hey @ovunccetin, the thing that was happening before was that routees were being monitored as both actors AND routees, it didn't seem to make much sense to record the actor metrics individually because from the rest of the application all you see is a router, and you never really care about how each routee is working or which of them receives the message you are sending as long as it is received a processed properly. Then we updated the instrumentation to ensure that each actor will be monitored as either an actor OR a routee, not both. Then, when that change was made the mailbox-size metric doesn't make sense anymore in a router, because the router itself doesn't have a mailbox and if you see a 100 there, it might actually be 20 messages on each of 5 routees behind the router.. the number would be incorrect.

As a workaround you could have a group (e.g. RoundRobinGroup) instead of a router, then all the "routees" are just regular actors and will be monitored as such, showing the respective mailbox sizes.

I saw that @pjfanning made a PR for bringing back `mailbox-size` to the router, maybe it would be a good idea to name it `work-queue-size` of `pending-work-size` or something similar, but definitely not mailbox-size as it wont be accurate.

Other than that, what are the cases in which the mailbox sizes of routees are relevant in your use case? We create routers when there is certain kind of work to be done, the work units are roughly the same in terms of complexity and time required to complete and we want to allow for parallelism to get the work done faster.. but then which actor gets it done becomes unimportant and the only important thing is that the router itself can process things fast enough. 

What do you guys think? how are you using routers?

**Comment by pjfanning** [comment]
Would this be best solved with the actor-groups? As @ivantopo highlights, for routees, it make sense to sum the data across all the routee actors.
In https://github.com/kamon-io/kamon-akka/pull/8, I have not allowed routee actors to be tracked in actor groups, but that can be changed.

**Comment by pjfanning** [comment]
@ovunccetin I have modified my pull request for actor groups to allow routee actors to be monitored as part of actor groups. The code is completely experimental but if you have a chance, could you have a look at https://github.com/pjfanning/kamon-akka-group and see if you can modify the HelloWorld actor sample to have a router and see if you can configure an actor-group metric four routee actors?

**Comment by ivantopo** [comment]
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!
