### ISSUE TITLE
No way to fully shut down Kamon 1.0

### ISSUE THREAD

**Issue by ruippeixotog** [kamon-io/Kamon#502]
There should be a way to completely shut down Kamon programatically, making the JVM terminate normally without recurring to explicit `System.exit` calls. With Kamon 1.0, unfortunately, I can't seem to do this:

```scala
object Main extends App {
  Kamon.loadReportersFromConfig() // this may even be an empty list of reporters
  Kamon.stopAllReporters()
  // the JVM should terminate after this
}
```

It seems that due to the `registryExecutionContext` inside `ReporterRegistry`, the JVM keeps active threads that prevent the JVM shutdown. We should be able to shut down the `registryExecutionContext` either by a `Kamon.stop()` method like before or by `stopAllReporters()`.

**Comment by ivantopo** [comment]
hello @ruippeixotog, thanks for reporting this! We will take a look it asap :)

**Comment by n1ko-w1ll** [comment]
oh yes, that's a show stopper for us. Since adding the Kamon dependency, there are more and more situations in which our application is not able to shutdown correctly. This is even more a problem because this is our way to reload the application if the configuration in Consul changes... application exits and is restarted by docker. Now the application tries to stop but keeps hanging in an undefined state.
