### ISSUE TITLE
Support adding logs to spans

### ISSUE THREAD

**Issue by japgolly** [kamon-io/Kamon#512]
OpenTracing, Jaeger et al support adding logs to spans. Kamon doesn't seem to yet support this.

Reference: https://github.com/opentracing/opentracing-java/blob/85433fce92575e31e362e46dd4b93f5d5883cb39/opentracing-api/src/main/java/io/opentracing/Span.java#L47-L113

**Comment by ivantopo** [comment]
Hey @japgolly! 

We explicitly decided not to add logs to Kamon spans because in our humble opinion that is a undesirable mix of concerns, logging is a pretty different problem than tracing and there are well defined APIs and tools for that, there is no need to convolute a Span with anything that is not directly related to distributed tracing. One thing that we indeed find valuable are "events" happening while the Span is in progress and we provide a very simple API for this, we call it [marks][1], those are equivalent to the simpler [overloads of log][2] in OpenTracing and they do get [reported to Jaeger][3] as logs and to [Zipkin as annotations][4].

We envision marks to be small strings, more like event identifiers as we do in our [Akka instrumentation][5] but there are no limits on what can be done with them. If you want, you can write a log appender that will write marks on the current span, or just write arbitrary marks from your code and they will end up showing in Jaeger, but instead of that what we advise to people is to log with context instead, you can include the trace ID in your log patterns and then any log aggregator can let you find all log lines containing that particular trace id.

So, long story short, there is partial support for OT logs through marks and we are definitely not thinking of changing this in the near future since we consciously took the decision not to mix logging and tracing. Hope this helps and thanks for asking :slightly_smiling_face: 

[1]: https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/trace/Span.scala#L46-L48
[2]: https://github.com/opentracing/opentracing-java/blob/85433fce92575e31e362e46dd4b93f5d5883cb39/opentracing-api/src/main/java/io/opentracing/Span.java#L85-L113
[3]: https://github.com/kamon-io/kamon-jaeger/blob/master/src/main/scala/kamon/jaeger/JaegerReporter.scala#L105-L112
[4]: https://github.com/kamon-io/kamon-zipkin/blob/master/src/main/scala/kamon/zipkin/Zipkin.scala#L80-L82
[5]: https://github.com/kamon-io/kamon-akka/blob/master/kamon-akka-2.5.x/src/main/scala/kamon/akka/instrumentation/ActorMonitor.scala#L101

**Comment by japgolly** [comment]
No worries and thanks for the explanation.
