### ISSUE TITLE
Build for Scala 2.13 (RC1 / RC2)

### ISSUE THREAD

**Issue by nmeln** [kamon-io/Kamon#587]
Do you plan to build kamon jars for Scala 2.13 and its release candidates? Final release is coming in a month or so. 

Would be nice to check if kamon works ok with new Scala. 
In our projects kamon is the only blocker for moving the build to 2.13-RC1.

**Comment by lvitaly** [comment]
Scala 2.13.0 is already released. Most of the libraries will publish 2.13.0 build in a few weeks. And it will be great if Kamon do the same 😇

**Comment by manub** [comment]
That would be greatly appreciated! Are there any blockers?

**Comment by francisdb** [comment]
I don't think there are for core Kamon
An akka version supporting 2.13 was also just released https://github.com/akka/akka/issues/26764

**Comment by ivantopo** [comment]
Hey folks! So far the only limitation is time.. I have been very deep into the final push for the 2.0 release and sort of missed lots of other stuff, including the 2.13 release. Core should be piece of cake, but other modules will depend, particularly the futures module since I know there were some changes around it but didn't manage to see what is there yet. Will keep you posted on progress!

**Comment by jtjeferreira** [comment]
fixed in https://github.com/kamon-io/Kamon/pull/590

**Comment by ivantopo** [comment]
As mentioned by @jtjeferreira, this was fixed and published already :tada:
