### ISSUE TITLE
Unable to run kamon 0.2.4 through sbt

### ISSUE THREAD

**Issue by ShengC** [kamon-io/Kamon#77]
First apologize if this is the wrong place to ask this question, original question is posted on stackoverflow: 
http://stackoverflow.com/questions/25436247/scala-kamon-start-error

stacktrace:
[error] [URLClassLoader@7333fb54] error Cannot instantiate message handler kamon.weaver.logging.KamonWeaverMessageHandler -- (ConfigException$Missing) No configuration setting found for key 'kamon'
[error] No configuration setting found for key 'kamon'
[error] com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'kamon'
[error]         at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
[error]         at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:218)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:224)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:33)
[error]         at kamon.weaver.logging.KamonWeaverMessageHandler.<init>(KamonWeaverMessageHandler.scala:30)
....

The weird thing is reference.conf is packed in kamon core jar, but still when the app got started through sbt, it could not find kamon config...

**Comment by slavaschmidt** [comment]
@ivantopo , you are absolutely right, the problem arises while using sbt-revolver plugin.

I was able to pinpoint the issue to the presence of the `-Xbootclasspath/a:`command line parameter of the forked process.

I think, through this some classes are able to escape AspectJ weaving. Probably, there is an easy way to fix this using some AspectJ configuration magic, but I wasn't able to achieve this.

What I did instead was:

1. Got rid of the `-Xbootclasspath/a:` parameter by adding following to the build.sbt: `Revolver.reForkOptions := Revolver.reForkOptions.value.copy(bootJars = Nil)`

2. Fixed `Error: Could not find or load main class scala.tools.nsc.MainGenericRunner`caused by (1.) through changing sat-revolver plugin's `spray.revolver.SbtCompatImpl` object to use `Fork.java` instead of `Fork.scala`.

After this, trace context was propagated as expected. Hope this makes sense and helps.

**Comment by yanns** [comment]
@slavaschmidt I have the same problem as you have with sbt revolver.
Can you explain how you changed the `spray.revolver.SbtCompatImpl` object to use `Fork.java` instead of `Fork.scala`?

**Comment by ivantopo** [comment]
Hey @slavaschmidt, I was investigating this issue today and found out that something like this is enough to make it work:

```scala
javaOptions in Revolver.reStart <++= AspectjKeys.weaverOptions in Aspectj
```

have you tried that? It seems to work nicely and doesn't require any changes to the `sbt-revolver` plugin!

**Comment by ivantopo** [comment]
Oh and @yanns, can you also give it a try please?

**Comment by yanns** [comment]
@ivantopo I am already using that and it is not sufficient.
It fixed the warning about the weaving, but the trace context with a `Future` is lost.

I pushed my test project on github if you want to try: https://github.com/yanns/kamon-revolver

**Comment by slavaschmidt** [comment]
@ivantopo That didn't work for me, but my setup is kind of special because i have a couple of another java agents which i configure using command line parameters

@yanns Sorry, but this will be a very short explanation. I changed a source code of the revolver plugin.

**Comment by yanns** [comment]
For info, I made a PR for sbt revolver to support `Fork.java`: https://github.com/spray/sbt-revolver/pull/47

**Comment by ivantopo** [comment]
nice @yanns! I'll keep an eye on that PR :)
