### ISSUE TITLE
Influx Integration Module

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/Kamon#79]

**Comment by sunnylbk** [comment]
+1

**Comment by pimeys** [comment]
I have a work in progress for this: https://github.com/pimeys/Kamon/tree/influxdb_support

We have this running on production, but I need to write some tests before I can provide a pull request for you. If you're in a hurry, please clone my fork and try it yourself. Comments are always welcome, if I missed some important feature.

**Comment by ivantopo** [comment]
@pimeys thanks for sharing that! What a nice coincidence that we were talking about how many modules have appeared over time, we just got a PR for Reimann and now there is also something already done for InfluxDB, awesome!

**Comment by pimeys** [comment]
Yeah. I have this code in our software and we get nicely the correct metrics. I'm planning to write some tests this week and build the influx module as a kamon jar file for us to use. After that I'm opening a pull request for you. This now works with influx http and udp interfaces, I can't test it with https, so that one is currently disabled.

**Comment by pimeys** [comment]
A WIP pull request for review. https://github.com/kamon-io/Kamon/pull/347

**Comment by pimeys** [comment]
The pull request over there is quite finished from my side. You can start testing with it, we run it already on production.

**Comment by dpsoft** [comment]
related to https://github.com/kamon-io/Kamon/pull/347
