### ISSUE TITLE
Caching Futures causes reusing TraceID of the cached request

### ISSUE THREAD

**Issue by dfic-mdsol** [kamon-io/Kamon#829]
I created sample project to reproduce the issue: https://github.com/dfic-mdsol/Cached-request-tracing-example
The endpoint makes two get requests, the first one is cached:
![image](https://user-images.githubusercontent.com/44581305/89916814-5a34bf00-dbf8-11ea-878e-8af5ccd0d1d6.png)
they are both visible in Zipkin for the first call:
![image](https://user-images.githubusercontent.com/44581305/89916283-bfd47b80-dbf7-11ea-8b6b-090579c171b3.png)
For the subsequent calls neither of the requests is visible in Zipkin
![image](https://user-images.githubusercontent.com/44581305/89916697-370a0f80-dbf8-11ea-8c20-4ace3900b67a.png)
The second request, which is not cached, is being reported with TraceID of the cached request, different from the TraceID returned in response headers, so it's not visible in Zipkin when searching using TraceID from the response header. This happens for all the incoming request for as long as the cache is populated.

The workaround is to cache values instead of Futures, but it has its own drawbacks. Are there any other options other than that? Is this a bug?

**Comment by yarosman** [comment]
Have the same problem using "com.github.ben-manes.caffeine" % "caffeine" % "3.0.2" directly

**Comment by SimunKaracic** [comment]
I'll tackle this at the end of the week/early next week, since it appears to be a popular issue :D

**Comment by yarosman** [comment]
> I'll tackle this at the end of the week/early next week, since it appears to be a popular issue :D

It would be great !)

**Comment by ivantopo** [comment]
Folks, this is going to be fixed with Kamon 2.2.0. Please take a look at [this comment](https://github.com/kamon-io/Kamon/issues/1021#issuecomment-853930200) (the entire thread might be interesting as well!)

Long story short is that the way the Kamon 2.x Future instrumentation works will never allow for Future values to be cached, because the Context is tied to the Future itself, not to the execution context in which Spans are created. I made an example similar to @dfic-mdsol's code above where I'm caching the value of the `FetchUser` Future, and here is how two different invocations of the same request look like:

![image](https://user-images.githubusercontent.com/1302854/120666162-ab19ea80-c48c-11eb-8cc5-cbfbd741e00e.png)
![image](https://user-images.githubusercontent.com/1302854/120666249-ba009d00-c48c-11eb-8171-e2edbe4c2403.png)

Notice how the first invocation has two `FetchCredentials` spans. The first Span should be there, but the second Span (marked in red) actually belongs to the second invocation, but got linked to the wrong trace because the value of `FetchUser` was cached.

---
Rolling back the instrumentation to 1.x style yields exactly what is expected:

The first invocation has the three spans:
![image](https://user-images.githubusercontent.com/1302854/120666708-1663bc80-c48d-11eb-813a-94a3a8199118.png)

The second invocation doesn't have the `FetchUser` call because it was never made (the value was cached), but has the `FetchCredentials` Span:
![image](https://user-images.githubusercontent.com/1302854/120667212-8eca7d80-c48d-11eb-8431-47f4002a930f.png)

Stay tuned for more details.

**Comment by yarosman** [comment]
@ivantopo when you are going to release Kamon 2.2.0 ?))

**Comment by ivantopo** [comment]
@yarosman not sure, maybe today or on Monday. We got 3 related PRs: #1033, #1034, and #1035. I'm confident about the first two, but still trying to figure out if the last one has everything we need.

**Comment by ivantopo** [comment]
Folks, I tried @dfic-mdsol's example with a local snapshot of #1035 and it worked exactly as expected:
![image](https://user-images.githubusercontent.com/1302854/120791010-ecb1a080-c533-11eb-96dd-255fb9ef0e01.png)

The first trace gets both `get` Spans, the second trace only gets the second.

**Comment by ivantopo** [comment]
Hey folks, this is fixed and released with Kamon [2.2.0](https://github.com/kamon-io/Kamon/releases/tag/v2.2.0). Please share if you find any issues with the new version!
