### ISSUE TITLE
Failed to read process file: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (deleted)

### ISSUE THREAD

**Issue by AlexITC** [kamon-io/Kamon#884]
Some months ago, I got a weird error in one of my apps, today, I got the same error in a different one, Kamon is a piece in both projects, I have no idea how something like this could ha occurred but I'm pasting the error just in case someone has any idea on preventing it.

```
Failed to read process file: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (deleted)
    at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:284)
    at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:224)
    at oshi.software.common.AbstractOperatingSystem.getProcess(AbstractOperatingSystem.java:221)
    at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.recordProcessULimits(ProcessMetricsCollector.scala:97)
    at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.$anonfun$schedule$1(ProcessMetricsCollector.scala:63)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
```

**Comment by dbwiddis** [comment]
The line number in this stack trace is indicative of OSHI version 4.2.1 or earlier.

**Comment by AlexITC** [comment]
I'll try upgrading, thanks.

**Comment by dbwiddis** [comment]
@AlexITC FYI, if you're only upgrading OSHI but keeping the older Kamon version you'll need to stay on 4.X, so I'd recommend 4.9.5.  Once you upgrade the Kamon version which depends on OSHI 5.x you'll need to upgrade that OSHI version (or just let it resolve transitively).

**Comment by AlexITC** [comment]
I don't depend on OSHI directly but use the kamon plugin for play, I'll try upgrading to the latest version, thanks for the hint.

**Comment by ivantopo** [comment]
Hey @AlexITC!

I saw [on Gitter](https://gitter.im/kamon-io/Kamon?at=6026d81c32e01b4f71905ec7) that you are still having this problem. Can you please share what Kamon versions and environment (java version, docker or not) where you using? I'm trying to reproduce the issue without any success.

**Comment by AlexITC** [comment]
These are the versions were the error is occurring:

```
kanela -> 2.0.7
kamon-bundle -> 2.1.11
kamon-apm-reporter -> 2.1.11
```

Thanks.

**Comment by ivantopo** [comment]
Can you please say more about the environment where it happens? I tried those versions during the weekend but couldn't reproduce the problem. If you are running on docker please share the base image and any special details you think can help us reproduce it :pray:

**Comment by dbwiddis** [comment]
OSHI maintainer here.  The root cause of this problem is described here: https://github.com/oshi/oshi/issues/1153

Per [`man proc`](http://man7.org/linux/man-pages/man5/proc.5.html) (emphasis mine):

> /proc/[pid]/exe
>               Under Linux 2.2 and later, this file is a symbolic link containing the actual pathname of the executed command.  This symbolic link can be dereferenced normally; attempting to open it will open the executable.  You can even type /proc/[pid]/exe to run another copy of the same executable that is being run by process [pid]. If the pathname has been unlinked, the symbolic link will contain the string '(deleted)' appended to the original pathname.  **In a multi‐threaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling pthread_exit(3)).**

So to reproduce, one should attempt to query the process bitness of a process whose main thread has terminated.

The log warning results from attempting to query process bitness reading the ELF header.  [Here is the line generating the log error](https://github.com/oshi/oshi/blob/oshi-parent-5.3.6/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L252) (in version 5.3.6 reported on gitter).

The bug reading `/proc/[pid]/exe` was fixed in OSHI 4.6.1.  The `path` variable referenced above is checked for the presence of " (deleted)" which is removed from the path:  [Here is the line where " (deleted)" is removed](https://github.com/oshi/oshi/blob/oshi-parent-5.3.6/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L283) in version 5.3.6.

Note that the new location (as of 5.X) of this log error and check is the `LinuxOSProcess` class.  However, the log message on gitter still appears to be coming from the `LinuxOperatingSystem` class, which is a 4.x and earlier issue.  **Bottom line: This log warning is not coming from OSHI 5.x.** 

I suspect there is a conflicting dependency on an earlier version (pre-4.6.1) of OSHI being loaded, possibly by another dependency.  Investigating transitive dependencies in @AlexITC'd `pom.xml` file will help figure out the problem.

**Comment by AlexITC** [comment]
Looks weird because I don't seem to have any other dependency bringing OSHI, running `sbt dependencyTree | grep -C 7 oshi` just leads to kamon bringing OSHI:

```
[info]   | +-io.kamon:kamon-core_2.13:2.1.11 [S]
[info]   |   +-com.typesafe:config:1.3.1 (evicted by: 1.4.0)
[info]   |   +-com.typesafe:config:1.4.0
[info]   |   +-org.slf4j:slf4j-api:1.7.25 (evicted by: 1.7.30)
[info]   |   +-org.slf4j:slf4j-api:1.7.30
[info]   |   
[info]   +-io.kamon:kamon-bundle_2.13:2.1.11 [S]
[info]   | +-com.github.oshi:oshi-core:5.3.6
[info]   | | +-net.java.dev.jna:jna-platform:5.6.0
[info]   | | | +-net.java.dev.jna:jna:5.6.0
[info]   | | | 
[info]   | | +-net.java.dev.jna:jna:5.6.0
[info]   | | +-org.slf4j:slf4j-api:1.7.30
[info]   | | 
[info]   | +-io.kamon:kamon-core_2.13:2.1.11 [S]
```

**Comment by dbwiddis** [comment]
Very odd.

Still, something must be amiss with the versioning.  The log warning you show on Gitter is:
```
2021-02-12 19:33:22,678 [WARN] from oshi.software.os.linux.LinuxOperatingSystem in Process Metrics - Failed to read process file: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (deleted)
```
The [only place in OSHI source code](https://github.com/oshi/oshi/search?q=%22Failed+to+read+process+file%22) that the string "Failed to read process file" occurs is in `LinuxOSProcess` (at line 253 in version 5.3.6).  It was moved there from `LinuxOperatingSystem` [as part of the refactoring for 5.0.0](https://github.com/oshi/oshi/pull/1191/files).  I've confirmed 'LinuxOSProcess` [is properly reporting the class name to the logging system](https://github.com/oshi/oshi/blob/oshi-parent-5.3.6/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L62).

The log warning outputs the `path` variable [which is only set in one place](https://github.com/oshi/oshi/blob/oshi-parent-5.3.6/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L279) and specifically searches for the `" (deleted)"` string and removes it.

Your report at the top of this issue includes line number 284 points to either [version 4.2.0](https://github.com/oshi/oshi/blob/oshi-parent-4.2.0/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L284) or [version 4.2.1](https://github.com/oshi/oshi/blob/oshi-parent-4.2.1/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L284).  You didn't post an updated stack trace on your most recent Gitter post to know if it's a different line, but the class name is enough to clearly point to a versioning issue somewhere.

Suggestions: 
 - clean out your dependency repository and let it be rebuilt
 - search your machine's fileysystem for `oshi-core-4.2.0.jar` or `oshi-core-4.2.1.jar` and delete them
 - double-check your own project's classpath/library loading and ensure there are no manual inclusions of other jar files
 - if all else fails, configure your logger to suppress log warnings from that class.  You'll get "0" instead of either 32 or 64 for process bitness on affected processes but won't be annoyed by log warnings.

**Comment by AlexITC** [comment]
I'll try to dig deeper on this later, just to confirm, the file isn't actually deleted but it is just a noisy log that shouldn't affect the app, right?

**Comment by dbwiddis** [comment]
Correct. What the `(deleted)` indicates is that the original executable starting the process has terminated, but still may be executing on a fork.  The only impact would be an incorrect value for "process bitness" for that terminated thread.

However, I was rereading gitter and saw this line in the hour preceding your report:
> I have reverted from 2.1.12 until 2.1.8 (one by one) which used to work fine

Kamon version 2.1.8 [used oshi-core-4.2.1 as a dependency](https://github.com/kamon-io/Kamon/blob/v2.1.8/build.sbt#L376).  This was updated to 5.3.6 in 2.1.9.

I strongly suspect your log error was associated with your (temporary, I assume) reversion to 2.1.8.

**Comment by AlexITC** [comment]
The reverts occurred locally only as those were related to a different [issue](https://github.com/kamon-io/kanela/issues/116).

Unfortunately, is really difficult to know which kamon version the app was using at the time of the issue, in any case, it hasn't occurred again, let's hope for that.

Thanks.

**Comment by AlexITC** [comment]
I think I found the reason, I'm using the play way that packages the app in a zip file, which includes a `lib` folder with all the transitive dependencies, unfortunately, my deployment script wasn't cleaning the app's directory on each deployment, hence, the new libraries would be placed there without removing the old ones, at the end, I ended up with these files in my `lib` folder:
```
com.github.oshi.oshi-core-4.2.1.jar
com.github.oshi.oshi-core-5.3.6.jar
```

So, @dbwiddis was right, I'll clean my spaces to avoid this issue.

Thanks!

**Comment by dbwiddis** [comment]
Thanks for your patience and persistence in figuring out the root cause.

**Comment by SimunKaracic** [comment]
Great job everyone, and thanks for the assist @dbwiddis :tada:

**Comment by ivantopo** [comment]
Hey @dbwiddis, I know a few months passed but I wanted to say this since back in March: thanks a lot for helping us out with this issue! :tada:

**Comment by dbwiddis** [comment]
No problem at all! Happy to help.
