### ISSUE TITLE
Metric jvm.memory.buffer-pool.count is captured as float

### ISSUE THREAD

**Issue by kunalherkal** [kamon-io/Kamon#910]
This metric was not present in `2.1.8` but was probably present in `1.x.x ` with value as an integer. After updating kamon dependencies to `2.1.9` I notice following errors in our logs. 
```
Metrics POST to InfluxDB failed with status code [400], response body: {"error":"partial write: field type conflict: input field \"value\" on measurement \"jvm.memory.buffer-pool.count\" is type float, already exists as type integer dropped=2"}
```
Here are the kamon dependencies we use:
```
"io.kamon" %% "kamon-bundle" % "2.1.9"
"io.kamon" %% "kamon-influxdb" % "2.1.9"
"io.kamon" %% "kamon-prometheus" % "2.1.9"
"io.kamon" % "kanela-agent" % "1.0.7"
```
Some of our teams still use `1.x.x` and some will soon start using `2.1.9`, so a fix/workaround is important. Thanks in advance!

**Comment by SimunKaracic** [comment]
This is happening because all Gauge instruments are now `Double`s, and we can't change something so that _only_ this specific metric is an `Int`.

There's two ways to fix this: 
1) Upgrade all your dependencies to Kamon 2.x
2) Change the `InfluxDb` reporter so it converts Gauge metrics to `Int`s. Probably hidden behind a setting, so we don't change the default behavior.

Option number 2 shouldn't be too hard to implement. Would you be interested in contributing something like that?

**Comment by kunalherkal** [comment]
@SimunKaracic Thank you for your reply! We decided that all our teams will migrate to Kamon 2.x, so that solves the problem for us.

**Comment by SimunKaracic** [comment]
Thanks for reporting back :)
